#! /bin/sh

### BEGIN INIT INFO
# Provides:          cubian-ondemandcpufreq
# Required-Start:    
# Required-Stop:
# Should-Start:      $all
# Default-Start: 2 3 4 5    
# Default-Stop:
# Short-Description: Adjust cpu frequency
# Description: Adjust CPU freqency on system up
### END INIT INFO

N=/etc/init.d/cubian-ondemandcpufreq

set -e

case "$1" in
  start)
	echo -n 25 > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold
	echo -n 10 > /sys/devices/system/cpu/cpufreq/ondemand/sampling_down_factor
	echo -n 1 > /sys/devices/system/cpu/cpufreq/ondemand/io_is_busy
	
	for cpu in $(ls /sys/devices/system/cpu/ | grep 'cpu[0-9][0-9]*');do
	  echo -n ondemand > /sys/devices/system/cpu/${cpu}/cpufreq/scaling_governor
	  echo -n 1008000 > /sys/devices/system/cpu/${cpu}/cpufreq/scaling_max_freq
	  echo -n 300000 > /sys/devices/system/cpu/${cpu}/cpufreq/scaling_min_freq
	done

	;;
  status)
	cpufreq-info
	;;
  *)
	echo "Usage: $N {start|status}" >&2
	exit 1
	;;
esac

exit 0
